-- phpMyAdmin SQL Dump
-- version 3.4.9
-- http://www.phpmyadmin.net
--
-- Host: helska.cefns.nau.edu
-- Generation Time: May 11, 2017 at 01:34 PM
-- Server version: 1.0.12
-- PHP Version: 5.3.3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `capstone_datavis`
--

-- --------------------------------------------------------

--
-- Table structure for table `stgpools`
--

CREATE TABLE IF NOT EXISTS `stgpools` (
  `CACHE` varchar(255) DEFAULT NULL,
  `MAXSIZE` varchar(255) DEFAULT NULL,
  `STGPOOL_NAME` varchar(255) DEFAULT NULL,
  `BUCKETNAME` varchar(255) DEFAULT NULL,
  `PROTECTLOCALSTGPOOLS` varchar(255) DEFAULT NULL,
  `COPYSTGPOOLS` varchar(255) DEFAULT NULL,
  `RECLAIMPROCESS` varchar(255) DEFAULT NULL,
  `TOTAL_SPACE_MB` varchar(255) DEFAULT NULL,
  `MIGCONTINUE` varchar(255) DEFAULT NULL,
  `NUMSCRATCHUSED` varchar(255) DEFAULT NULL,
  `MIGDELAY` varchar(255) DEFAULT NULL,
  `DEVCLASS` varchar(255) DEFAULT NULL,
  `OVFLOCATION` varchar(255) DEFAULT NULL,
  `CLOUD_LOCATION` varchar(255) DEFAULT NULL,
  `CLOUD_TYPE` varchar(255) DEFAULT NULL,
  `LOCAL_EST_CAPACITY_MB` varchar(255) DEFAULT NULL,
  `PCT_LOGICAL` varchar(255) DEFAULT NULL,
  `NEXTSTGPOOL` varchar(255) DEFAULT NULL,
  `DEDUP_REQ_BKUP` varchar(255) DEFAULT NULL,
  `PROTECTPROCESS` varchar(255) DEFAULT NULL,
  `REUSEDELAY` varchar(255) DEFAULT NULL,
  `LASTPROTECT_DATE` varchar(255) DEFAULT NULL,
  `HIGHMIG` varchar(255) DEFAULT NULL,
  `LOCAL_PCT_UTILIZED` varchar(255) DEFAULT NULL,
  `CHG_ADMIN` varchar(255) DEFAULT NULL,
  `SPACE_SAVED_MB` varchar(255) DEFAULT NULL,
  `RECLAIMSTGPOOL` varchar(255) DEFAULT NULL,
  `MAXSCRATCH` varchar(255) DEFAULT NULL,
  `ACCESS` varchar(255) DEFAULT NULL,
  `MIGR_RUNNING` varchar(255) DEFAULT NULL,
  `CLOUD_URL` varchar(255) DEFAULT NULL,
  `ACTIVEDATASTGPOOLS` varchar(255) DEFAULT NULL,
  `COMPRESSED` varchar(255) DEFAULT NULL,
  `PCT_MIGR` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `MIGR_MB` varchar(255) DEFAULT NULL,
  `STG_TYPE` varchar(255) DEFAULT NULL,
  `COPYCONTINUE` varchar(255) DEFAULT NULL,
  `TOTAL_UNUSED_PENDING_MB` varchar(255) DEFAULT NULL,
  `POOLTYPE` varchar(255) DEFAULT NULL,
  `SHRED_COUNT` varchar(255) DEFAULT NULL,
  `OFFSITERCLMLIMIT` varchar(255) DEFAULT NULL,
  `DATAFORMAT` varchar(255) DEFAULT NULL,
  `RECLAMATIONTYPE` varchar(255) DEFAULT NULL,
  `RECL_RUNNING` varchar(255) DEFAULT NULL,
  `PROTECTSTGPOOL` varchar(255) DEFAULT NULL,
  `AUTOCOPY` varchar(255) DEFAULT NULL,
  `EST_CAPACITY_MB` varchar(255) DEFAULT NULL,
  `SPACE_USED_FOR_PROTECTED_DATA` varchar(255) DEFAULT NULL,
  `CRCDATA` varchar(255) DEFAULT NULL,
  `MIGR_SECONDS` varchar(255) DEFAULT NULL,
  `HAS_CLIENT_DEDUP_DATA` varchar(255) DEFAULT NULL,
  `MIGPROCESS` varchar(255) DEFAULT NULL,
  `DEDUP_SPACE_SAVED_MB` varchar(255) DEFAULT NULL,
  `CLOUD_ID` varchar(255) DEFAULT NULL,
  `CHG_TIME` varchar(255) DEFAULT NULL,
  `RECLAIM` varchar(255) DEFAULT NULL,
  `LASTPROTECTLOCAL_DATE` varchar(255) DEFAULT NULL,
  `TRIGGER_PCT_UTIL` varchar(255) DEFAULT NULL,
  `COMP_SPACE_SAVED_MB` varchar(255) DEFAULT NULL,
  `RECLAIM_LIMIT` varchar(255) DEFAULT NULL,
  `MAX_WRITERS` varchar(255) DEFAULT NULL,
  `ENCRYPTED` varchar(255) DEFAULT NULL,
  `PCT_UTILIZED` varchar(255) DEFAULT NULL,
  `COLLOCATE` varchar(255) DEFAULT NULL,
  `LOWMIG` varchar(255) DEFAULT NULL,
  `LOCAL_PCT_LOGICAL` varchar(255) DEFAULT NULL,
  `DEDUPLICATE` varchar(255) DEFAULT NULL,
  `IDENTIFYPROCESS` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `stgpools`
--

INSERT INTO `stgpools` (`CACHE`, `MAXSIZE`, `STGPOOL_NAME`, `BUCKETNAME`, `PROTECTLOCALSTGPOOLS`, `COPYSTGPOOLS`, `RECLAIMPROCESS`, `TOTAL_SPACE_MB`, `MIGCONTINUE`, `NUMSCRATCHUSED`, `MIGDELAY`, `DEVCLASS`, `OVFLOCATION`, `CLOUD_LOCATION`, `CLOUD_TYPE`, `LOCAL_EST_CAPACITY_MB`, `PCT_LOGICAL`, `NEXTSTGPOOL`, `DEDUP_REQ_BKUP`, `PROTECTPROCESS`, `REUSEDELAY`, `LASTPROTECT_DATE`, `HIGHMIG`, `LOCAL_PCT_UTILIZED`, `CHG_ADMIN`, `SPACE_SAVED_MB`, `RECLAIMSTGPOOL`, `MAXSCRATCH`, `ACCESS`, `MIGR_RUNNING`, `CLOUD_URL`, `ACTIVEDATASTGPOOLS`, `COMPRESSED`, `PCT_MIGR`, `DESCRIPTION`, `MIGR_MB`, `STG_TYPE`, `COPYCONTINUE`, `TOTAL_UNUSED_PENDING_MB`, `POOLTYPE`, `SHRED_COUNT`, `OFFSITERCLMLIMIT`, `DATAFORMAT`, `RECLAMATIONTYPE`, `RECL_RUNNING`, `PROTECTSTGPOOL`, `AUTOCOPY`, `EST_CAPACITY_MB`, `SPACE_USED_FOR_PROTECTED_DATA`, `CRCDATA`, `MIGR_SECONDS`, `HAS_CLIENT_DEDUP_DATA`, `MIGPROCESS`, `DEDUP_SPACE_SAVED_MB`, `CLOUD_ID`, `CHG_TIME`, `RECLAIM`, `LASTPROTECTLOCAL_DATE`, `TRIGGER_PCT_UTIL`, `COMP_SPACE_SAVED_MB`, `RECLAIM_LIMIT`, `MAX_WRITERS`, `ENCRYPTED`, `PCT_UTILIZED`, `COLLOCATE`, `LOWMIG`, `LOCAL_PCT_LOGICAL`, `DEDUPLICATE`, `IDENTIFYPROCESS`) VALUES
('', '', 'ARCHFILEPOOL', '', '', '', '1', '', 'YES', '2', '0', 'FILEDEV', '', '', '', '', '100.0', 'LARGEFILEPOOL', '', '', '0', '', '60', '', 'TAODA', '', '', '5', 'READWRITE', 'NO', '', '', '', '22.9', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '20461.0', '', 'NO', '0', 'No', '5', '', '', '2015-10-22 10:52:16', '60', '', '57.4', '', '', '', '', '22.9', 'NO', '10', '', 'NO', ''),
('NO', '', 'ARCHIVEPOOL', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', 'ARCHFILEPOOL', '', '', '', '', '60', '', 'TAODA', '', '', '', 'READWRITE', 'NO', '', 'ADPPOOL', '', '20.2', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '3', '', 'NATIVE', '', '', '', 'Client', '20000.0', '', 'NO', '0', 'No', '4', '', '', '2015-10-21 19:13:17', '', '', '20.2', '', '', '', '', '20.2', '', '10', '', 'NO', ''),
('NO', '', 'BACKUPPOOL', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', 'BKFILEPOOL', '', '', '', '', '60', '', 'ADMIN', '', '', '', 'READWRITE', 'NO', '', 'ADPPOOL', '', '8.9', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '20000.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-09 09:05:56', '', '', '8.9', '', '', '', '', '8.9', '', '10', '', 'NO', ''),
('', '', 'BKFILEPOOL', '', '', '', '5', '', 'YES', '6', '0', 'FILEDEV', '', '', '', '', '100.0', 'LARGEFILEPOOL', '', '', '0', '', '60', '', 'TAODA', '', '', '15', 'READWRITE', 'NO', '', '', '', '25.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '61403.4', '', 'NO', '0', 'No', '5', '', '', '2015-10-15 10:39:17', '30', '', '62.6', '', '', '', '', '25.0', 'NO', '10', '', 'NO', ''),
('', '', 'BUCKET-TEST-1', 'ibmsp.d2158cfbf224e511bbfe40f2e9f58cf2', '', '', '', '0', '', '', '', '', '', 'OFFPREMISE', 'S3', '', '100.0', '', '', '', '1', '', '', '', 'TAODA', '0', '', '', 'READWRITE', '', 'http://9.11.60.236', '', 'YES', '', 'Has the same designated bucket as HYBRID-CLOUD-1, should generate an error that bucket name is invalid!', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'OBZwJgRcSWJg9WYEQsi2', '2016-08-02 13:58:17', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '', 'YES', ''),
('', '', 'CLEVER-1', 'ibmsp.d2158cfbf224e511bbfe40f2e9f58cf2', '', '', '', '10718', '', '', '', '', '', 'ONPREMISE', 'S3', '', '100.0', '', '', '', '1', '', '', '', 'TAODA', '40145', '', '', 'READWRITE', '', 'http://cs-accesser4.storage.tucson.ibm.com', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '6247', 'OBZwJgRcSWJg9WYEQsi2', '2016-02-18 11:12:08', '', '', '', '33899', '', 'NOLIMIT', 'No', '', '', '', '', 'YES', ''),
('', '', 'CLEVER-2', 'ibmsp.d2158cfbf224e511bbfe40f2e9f58cf2', '', '', '', '11534', '', '', '', '', '', 'ONPREMISE', 'S3', '', '100.0', '', '', '', '1', '', '', '', 'TAODA', '0', '', '', 'READWRITE', '', 'http://cs-accesser4.storage.tucson.ibm.com', '', 'NO', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'OBZwJgRcSWJg9WYEQsi2', '2016-02-18 11:13:04', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '', 'YES', ''),
('', '', 'CLEVER-BAD-1', 'ibmsp.d2158cfbf224e511bbfe40f2e9f58cf2', '', '', '', '0', '', '', '', '', '', 'ONPREMISE', 'S3', '', '100.0', '', '', '', '1', '', '', '', 'TAODA', '0', '', '', 'READWRITE', '', 'http://bad.url.bad', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'doesntMatter', '2016-02-18 13:03:02', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '', 'YES', ''),
('', '', 'CLOUDPOOL-1', '', '', '', '', '89718', '', '', '', '', '', 'ONPREMISE', 'SWIFT', '', '100.0', '', '', '', '0', '', '', '', 'TAODA', '2456', '', '', 'READWRITE', '', 'http://9.11.66.234:5000/v2.0/', '', 'NO', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '2456', 'admin:admin', '2016-02-10 10:53:29', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '', 'YES', ''),
('', '', 'CLOUDPOOL-2', '', '', '', '', '0', '', '', '', '', '', 'ONPREMISE', 'SWIFT', '', '100.0', '', '', '', '1', '', '', '', 'DELENCE', '0', '', '', 'READWRITE', '', 'http://9.11.66.234:5000/v2.0/', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'admin:admin', '2016-05-19 17:39:35', '', '', '', '0', '', 'NOLIMIT', 'No', '', '', '', '', 'YES', ''),
('', '', 'CLOUDPOOLENC-1', '', '', '', '', '0', '', '', '', '', '', 'OFFPREMISE', 'SWIFT', '', '100.0', '', '', '', '1', '', '', '', 'DELENCE', '0', '', '', 'READWRITE', '', 'http://9.11.66.234:5000/v2.0', '', 'NO', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'admin:admin', '2016-05-19 17:38:49', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '', 'YES', ''),
('', '', 'CONVERT-FROM-1', '', '', '', '1', '', 'YES', '0', '0', 'CONVERT-DEV', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '100000000', 'CONVERSIONCOMPLETE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2016-05-16 13:32:18', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'CONVERT-FROM-2', '', '', '', '1', '', 'YES', '0', '0', 'CONVERT-DEV', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '100000000', 'CONVERSIONCOMPLETE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2016-05-16 14:37:17', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'CONVERT-TEST-1', '', '', '', '1', '', 'YES', '0', '0', 'CONVERT-DEV', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '0', '', '100000000', 'CONVERSIONCOMPLETE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '0', '', '2016-05-16 12:03:16', '60', '', '0.0', '0', '', '', '', '0.0', 'GROUP', '70', '', 'YES', '1'),
('', '', 'COPY-PAYTON2', '', '', '', '', '', '', '0', '', 'VTL-3584-TSMGUI11-DEV', '', '', '', '', '', '', '', '5', '0', '', '', '', 'TAODA', '', '', '100000000', 'READWRITE', '', '', '', '', '', 'Copy of container pool PAYTON2', '', 'DEVCLASS', '', '', 'COPYCONTAINER', '', '', 'NATIVE', '', '', '', '', '0.0', '', '', '', '', '', '', '', '2016-07-27 12:17:21', '100', '', '', '', 'NOLIMIT', '', '', '0.0', '', '', '', 'NO', ''),
('', '', 'COPY-TAPE-TSMGUI11', '', '', '', '1', '', '', '6', '', 'VLT1-TSMGUI11-DEV', '', '', '', '', '100.0', '', '', '', '0', '', '', '', 'TAODA', '', '', '100', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPY', '', 'NOLIMIT', 'NATIVE', 'THRESHOLD', 'NO', '', '', '105725267.7', '', 'NO', '', 'No', '', '', '', '2016-06-27 16:17:07', '100', '', '', '', '', '', '', '0.4', 'NO', '', '', 'NO', ''),
('', '', 'COPY-TEST1', '', '', '', '', '', '', '0', '', 'VTL-3584-TSMGUI11-DEV', '', '', '', '', '', '', '', '5', '0', '', '', '', 'TAODA', '', '', '100000000', 'READWRITE', '', '', '', '', '', 'Copy of container pool TEST1', '', 'DEVCLASS', '', '', 'COPYCONTAINER', '', '', 'NATIVE', '', '', '', '', '0.0', '', '', '', '', '', '', '', '2016-07-27 12:27:18', '100', '', '', '', 'NOLIMIT', '', '', '0.0', '', '', '', 'NO', ''),
('', '', 'COPYPOOL', '', '', '', '5', '', '', '1', '', 'FILEDEV', '', '', '', '', '100.0', '', '', '', '0', '', '', '', 'ADMIN', '0', '', '20', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPY', '', 'NOLIMIT', 'NATIVE', 'THRESHOLD', 'NO', '', '', '81920.0', '', 'NO', '', 'No', '', '0', '', '2015-07-09 09:05:56', '50', '', '0.0', '0', '', '', '', '0.0', 'NO', '', '', 'YES', '4'),
('', '', 'COPYTOTAPE1', '', '', '', '', '', '', '0', '', 'VLT1-TSMGUI11-DEV', '', '', '', '', '', '', '', '1', '0', '', '', '', 'TAODA', '', '', '2', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPYCONTAINER', '', '', 'NATIVE', '', '', '', '', '0.0', '', '', '', '', '', '', '', '2016-06-28 10:36:17', '60', '', '', '', 'NOLIMIT', '', '', '0.0', '', '', '', 'NO', ''),
('', '', 'COPYTOTAPEOFF1', '', '', '', '', '', '', '1', '', 'VLT1-TSMGUI11-DEV', '', '', '', '', '', '', '', '1', '0', '', '', '', 'TAODA', '', '', '5', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPYCONTAINER', '', '', 'NATIVE', '', '', '', '', '7152557.4', '', '', '', '', '', '', '', '2016-07-13 09:16:12', '60', '', '', '', 'NOLIMIT', '', '', '0.7', '', '', '', 'NO', ''),
('', '', 'COPYTOTAPEON1', '', '', '', '', '', '', '1', '', 'VLT1-TSMGUI11-DEV', '', '', '', '', '', '', '', '1', '0', '', '', '', 'TAODA', '', '', '5', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPYCONTAINER', '', '', 'NATIVE', '', '', '', '', '7152557.4', '', '', '', '', '', '', '', '2016-07-01 13:20:50', '60', '', '', '', 'NOLIMIT', '', '', '0.7', '', '', '', 'NO', ''),
('', '', 'CTT-TEST-PAYTON1', '', '', '', '', '', '', '0', '', 'VTL-3584-TSMGUI11-DEV', '', '', '', '', '', '', '', '5', '0', '', '', '', 'TAODA', '', '', '100000000', 'READWRITE', '', '', '', '', '', 'Copy of container pool PAYTON1', '', 'DEVCLASS', '', '', 'COPYCONTAINER', '', '', 'NATIVE', '', '', '', '', '0.0', '', '', '', '', '', '', '', '2016-08-04 12:18:02', '60', '', '', '', 'NOLIMIT', '', '', '0.0', '', '', '', 'NO', ''),
('', '', 'CTTTEST-PAYTON3', '', '', '', '', '', '', '0', '', 'VTL-3584-TSMGUI11-DEV', '', '', '', '', '', '', '', '5', '0', '', '', '', 'TAODA', '', '', '100000000', 'READWRITE', '', '', '', '', '', 'Copy of container pool PAYTON3', '', 'DEVCLASS', '', '', 'COPYCONTAINER', '', '', 'NATIVE', '', '', '', '', '0.0', '', '', '', '', '', '', '', '2016-08-04 12:19:05', '60', '', '', '', 'NOLIMIT', '', '', '0.0', '', '', '', 'NO', ''),
('', '', 'DELCONVERT', '', '', '', '1', '', 'YES', '0', '0', 'FILELARGE', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'DELENCE', '0', '', '100000000', 'CONVERSIONCOMPLETE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '0', '', '2016-03-24 12:24:17', '60', '', '0.0', '0', '', '', '', '0.0', 'GROUP', '70', '', 'YES', '1'),
('', '', 'DIRPOOL-1', '', 'OFF-SITE-DIRPOOL-1', '', '', '', '', '', '', '', '', '', '', '', '', 'BACKUPPOOL', '', '', '0', '', '', '', 'TAODA', '1240919', '', '', 'READWRITE', '', '', '', 'YES', '', '', '', 'DIRECTORY', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', 'DIRPOOL-3', '', '501382.0', '', 'NO', '', '', '', '1181462', '', '2016-07-27 16:02:20', '', '2016-10-07 08:33:48', '', '59457', '', 'NOLIMIT', '', '12.6', '', '', '', 'YES', ''),
('NO', '', 'DISK_FINANCE_1', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', '', '', '', '', '', '90', '', 'TAODA', '', '', '', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:31', '', '', '0.0', '', '', '', '', '0.0', '', '70', '', 'NO', ''),
('NO', '', 'DISK_HUMAN_RESOURCES_1', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', '', '', '', '', '', '90', '', 'TAODA', '', '', '', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:09', '', '', '0.0', '', '', '', '', '0.0', '', '70', '', 'NO', ''),
('NO', '', 'DISK_HUMAN_RESOURCES_2', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', '', '', '', '', '', '90', '', 'TAODA', '', '', '', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:25', '', '', '0.0', '', '', '', '', '0.0', '', '70', '', 'NO', ''),
('NO', '', 'DISK_MANUFACTURING_1', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', '', '', '', '', '', '90', '', 'TAODA', '', '', '', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:14:46', '', '', '0.0', '', '', '', '', '0.0', '', '70', '', 'NO', ''),
('NO', '', 'DISK_MANUFACTURING_2', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', '', '', '', '', '', '90', '', 'TAODA', '', '', '', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:24', '', '', '0.0', '', '', '', '', '0.0', '', '70', '', 'NO', ''),
('NO', '', 'DISK_MARKETING_1', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', '', '', '', '', '', '90', '', 'TAODA', '', '', '', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:14:48', '', '', '0.0', '', '', '', '', '0.0', '', '70', '', 'NO', ''),
('NO', '', 'DISK_OPERATIONS_1', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', '', '', '', '', '', '90', '', 'TAODA', '', '', '', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:14:50', '', '', '0.0', '', '', '', '', '0.0', '', '70', '', 'NO', ''),
('', '', 'FILEBKDB_ACCOUNTING_1', '', '', '', '1', '', 'YES', '0', '0', 'FILEBKDB', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '27', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:14:52', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'FILEBKDB_LEGAL_1', '', '', '', '1', '', 'YES', '0', '0', 'FILEBKDB', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '37', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:13', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'FILEBKDB_MARKETING_1', '', '', '', '1', '', '', '0', '', 'FILEBKDB', '', '', '', '', '0.0', '', '', '', '0', '', '', '', 'TAODA', '', '', '87', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPY', '', 'NOLIMIT', 'NATIVE', 'THRESHOLD', 'NO', '', '', '0.0', '', 'NO', '', 'No', '', '', '', '2015-07-10 11:15:33', '100', '', '0.0', '', '', '', '', '0.0', 'NO', '', '', 'NO', ''),
('', '', 'FILEBKDB_MARKETING_2', '', '', '', '1', '', 'YES', '0', '0', 'FILEBKDB', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '97', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:35', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'FILEBKDB_PAYROLL_1', '', '', '', '1', '', '', '0', '', 'FILEBKDB', '', '', '', '', '0.0', '', '', '', '0', '', '', '', 'TAODA', '', '', '25', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPY', '', 'NOLIMIT', 'NATIVE', 'THRESHOLD', 'NO', '', '', '0.0', '', 'NO', '', 'No', '', '', '', '2015-07-10 11:15:22', '100', '', '0.0', '', '', '', '', '0.0', 'NO', '', '', 'NO', ''),
('', '', 'FILEBKDB_SALES_1', '', '', '', '1', '', 'YES', '0', '0', 'FILEBKDB', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '29', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:29', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'FILEDEV_ACCOUNTING_1', '', '', '', '1', '', '', '0', '', 'FILEDEV', '', '', '', '', '0.0', '', '', '', '0', '', '', '', 'TAODA', '', '', '45', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPY', '', 'NOLIMIT', 'NATIVE', 'THRESHOLD', 'NO', '', '', '0.0', '', 'NO', '', 'No', '', '', '', '2015-07-10 11:14:54', '100', '', '0.0', '', '', '', '', '0.0', 'NO', '', '', 'NO', ''),
('', '', 'FILEDEV_ACCOUNTING_2', '', '', '', '1', '', '', '0', '', 'FILEDEV', '', '', '', '', '0.0', '', '', '', '0', '', '', '', 'TAODA', '', '', '42', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPY', '', 'NOLIMIT', 'NATIVE', 'THRESHOLD', 'NO', '', '', '0.0', '', 'NO', '', 'No', '', '', '', '2015-07-10 11:15:17', '100', '', '0.0', '', '', '', '', '0.0', 'NO', '', '', 'NO', ''),
('', '', 'FILEDEV_FINANCE_1', '', '', '', '1', '', 'YES', '0', '0', 'FILEDEV', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '79', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:27', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'FILEDEV_HUMAN_RESOURCES_1', '', '', '', '1', '', 'YES', '0', '0', 'FILEDEV', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '84', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:37', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'FILEDEV_HUMAN_RESOURCES_2', '', '', '', '1', '', '', '0', '', 'FILEDEV', '', '', '', '', '0.0', '', '', '', '0', '', '', '', 'TAODA', '', '', '30', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPY', '', 'NOLIMIT', 'NATIVE', 'THRESHOLD', 'NO', '', '', '0.0', '', 'NO', '', 'No', '', '', '', '2015-07-10 11:15:38', '100', '', '0.0', '', '', '', '', '0.0', 'NO', '', '', 'NO', ''),
('', '', 'FILEDEV_INFORMATION_SYSTEMS_1', '', '', '', '1', '', '', '0', '', 'FILEDEV', '', '', '', '', '0.0', '', '', '', '0', '', '', '', 'TAODA', '', '', '19', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPY', '', 'NOLIMIT', 'NATIVE', 'THRESHOLD', 'NO', '', '', '0.0', '', 'NO', '', 'No', '', '', '', '2015-07-10 11:15:20', '100', '', '0.0', '', '', '', '', '0.0', 'NO', '', '', 'NO', ''),
('', '', 'FILEDEV_MANUFACTURING_1', '', '', '', '1', '', 'YES', '0', '0', 'FILEDEV', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '27', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:11', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'FILEDEV_SALES_1', '', '', '', '1', '', 'YES', '0', '0', 'FILEDEV', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '44', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:05', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'FILELARGE_FINANCE_1', '', '', '', '1', '', 'YES', '0', '0', 'FILELARGE', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '64', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:18', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'FILELARGE_LEGAL_1', '', '', '', '1', '', '', '0', '', 'FILELARGE', '', '', '', '', '0.0', '', '', '', '0', '', '', '', 'TAODA', '', '', '95', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', '', '', 'COPY', '', 'NOLIMIT', 'NATIVE', 'THRESHOLD', 'NO', '', '', '0.0', '', 'NO', '', 'No', '', '', '', '2015-07-10 11:15:14', '100', '', '0.0', '', '', '', '', '0.0', 'NO', '', '', 'NO', ''),
('', '', 'FILELARGE_SALES_1', '', '', '', '1', '', 'YES', '0', '0', 'FILELARGE', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '74', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-10 11:15:07', '60', '', '0.0', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'GERGANA_BAD_COPY', '', '', '', '1', '', '', '0', '', 'FILEDEV', '', '', '', '', '0.0', '', '', '', '0', '', '', '', 'CRAIG', '', '', '0', 'READWRITE', '', '', '', '', '', 'Test error flags for copy pools setup', '', 'DEVCLASS', '', '', 'COPY', '', 'NOLIMIT', 'NATIVE', 'THRESHOLD', 'NO', '', '', '0.0', '', 'NO', '', 'No', '', '', '', '2016-06-13 11:12:11', '100', '', '0.0', '', '', '', '', '0.0', 'NO', '', '', 'NO', ''),
('', '', 'HYBRID-CLOUD-1', 'ibmsp.d2158cfbf224e511bbfe40f2e9f58cf2', '', '', '', '7801', '', '', '', '', '', 'ONPREMISE', 'S3', '501383.0', '', '', '', '', '1', '', '', '0.0', 'TAODA', '82408', '', '', 'READWRITE', '', 'http://9.11.60.236', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '2474', 'OBZwJgRcSWJg9WYEQsi2', '2016-06-30 07:52:05', '', '', '', '79934', '', 'NOLIMIT', 'No', '', '', '', '0.0', 'YES', ''),
('', '', 'HYBRID-CLOUD2', 'ibmsp.d2158cfbf224e511bbfe40f2e9f58cf2', '', '', '', '0', '', '', '', '', '', 'ONPREMISE', 'S3', '501383.0', '', '', '', '', '1', '', '', '0.0', 'TAODA', '0', '', '', 'READWRITE', '', 'http://9.11.60.236', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'OBZwJgRcSWJg9WYEQsi2', '2016-06-30 07:52:42', '', '', '', '0', '', 'NOLIMIT', 'No', '', '', '', '0.0', 'YES', ''),
('', '', 'JDTANGPOOOL', 'ibmsp.d2158cfbf224e511bbfe40f2e9f58cf2', '', '', '', '0', '', '', '', '', '', 'OFFPREMISE', 'S3', '9956.0', '', '', '', '', '1', '', '', '0.0', 'GMARKOVA', '0', '', '', 'READWRITE', '', 'https://s3-us-west-2.amazonaws.com', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'yu', '2016-09-16 11:51:41', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '0.0', 'YES', ''),
('NO', '', 'JUSTINGAWESOMEPOOL', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', 'ARCHFILEPOOL', '', '', '', '', '90', '', 'JSTEASLE', '', '', '', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2016-04-04 13:46:39', '', '', '0.0', '', '', '', '', '0.0', '', '70', '', 'NO', ''),
('', '', 'LARGEFILEPOOL', '', '', '', '10', '', 'YES', '12', '0', 'FILELARGE', '', '', '', '', '100.0', '', '', '', '0', '', '60', '', 'TAODA', '144954', '', '45', 'READWRITE', 'NO', '', '', '', '21.4', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '360411.3', '', 'NO', '0', 'Yes', '1', '144954', '', '2016-02-02 10:54:34', '30', '', '80.0', '0', '', '', '', '21.4', 'NO', '10', '', 'YES', '5'),
('', '', 'NASLEGACYPOOL-1', '', '', '', '', '', '', '3', '', 'NASLEGACYDEV', '', '', '', '', '100.0', '', '', '', '0', '', '', '', 'TAODA', '', '', '4', 'READONLY', '', '', '', '', '', '', '', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NETAPPDUMP', 'THRESHOLD', '', '', '', '79698.7', '', 'NO', '', 'No', '', '', '', '2016-05-02 13:51:55', '', '', '', '', '', '', '', '62.2', 'GROUP', '', '', 'NO', ''),
('', '', 'NASPOOL-1', '', '', '', '', '', '', '1', '', 'NASDEV', '', '', '', '', '100.0', '', '', '', '0', '', '', '', 'TAODA', '', '', '100000000', 'READWRITE', '', '', '', '', '', '', '', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NETAPPDUMP', 'THRESHOLD', '', '', '', '4207162500000.0', '', 'NO', '', 'No', '', '', '', '2015-09-22 14:25:15', '', '', '', '', '', '', '', '0.0', 'GROUP', '', '', 'NO', ''),
('', '', 'NOT-HYBRID-1', '', '', '', '', '0', '', '', '', '', '', 'ONPREMISE', 'SWIFT', '', '100.0', '', '', '', '1', '', '', '', 'TAODA', '0', '', '', 'READWRITE', '', 'http://test.test.test', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'test', '2016-07-15 15:08:14', '', '', '', '0', '', 'NOLIMIT', 'No', '', '', '', '', 'YES', ''),
('', '', 'OFF-SITE-DIRPOOL-1', '', '', '', '', '', '', '5', '', 'VTL-3584-TSMGUI11-DEV', '', '', '', '', '', '', '', '5', '0', '', '', '', 'TAODA', '', '', '100000000', 'READWRITE', '', '', '', '', '', 'Copy of container pool DIRPOOL-1', '', 'DEVCLASS', '', '', 'COPYCONTAINER', '', '', 'NATIVE', '', '', '', '', '72759437561035.2', '', '', '', '', '', '', '', '2016-07-27 12:01:49', '100', '', '', '', 'NOLIMIT', '', '', '0.0', '', '', '', 'NO', ''),
('', '', 'PAYTON-CLOUD-1', '', '', '', '', '0', '', '', '', '', '', 'ONPREMISE', 'SWIFT', '432835.0', '', '', '', '', '1', '', '', '0.0', 'EVAN', '0', '', '', 'READONLY', '', 'HTTP://TEST.TEST|HTTP://TEST', '', 'NO', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'test', '2016-05-17 15:29:32', '', '', '', '0', '', 'NOLIMIT', 'No', '', '', '', '0.0', 'YES', ''),
('', '', 'PAYTON-CLOUD-2', 'ibmsp.d2158cfbf224e511bbfe40f2e9f58cf2', '', '', '', '0', '', '', '', '', '', 'OFFPREMISE', 'S3', '', '100.0', '', '', '', '1', '', '', '', 'GMARKOVA_MON', '0', '', '', 'UNAVAILABLE', '', 'http://test', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'test', '2016-04-20 20:51:52', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '', 'YES', ''),
('', '', 'PAYTON1', '', 'CTT-TEST-PAYTON1', '', '', '', '', '', '', '', '', '', '', '', '', 'ARCHFILEPOOL', '', '', '1', '2016-09-16 12:00:04', '', '', 'TAODA', '0', '', '', 'READWRITE', '', '', '', 'YES', '', '', '', 'DIRECTORY', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', 'DIRPOOL-3', '', '0.0', '', 'NO', '', '', '', '0', '', '2016-08-04 12:18:02', '', '2016-10-07 08:33:48', '', '0', '', 'NOLIMIT', '', '0.0', '', '', '', 'YES', ''),
('', '', 'PAYTON2', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '2016-09-16 12:00:04', '', '', 'TAODA', '0', '', '', 'READWRITE', '', '', '', 'YES', '', '', '', 'DIRECTORY', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', 'DIRPOOL-3', '', '0.0', '', 'NO', '', '', '', '0', '', '2016-08-16 14:19:48', '', '2016-08-08 19:31:01', '', '0', '', 'NOLIMIT', '', '0.0', '', '', '', 'YES', ''),
('', '', 'PAYTON3', '', 'CTTTEST-PAYTON3', '', '', '', '', '', '', '', '', '', '', '', '', 'ARCHFILEPOOL', '', '', '1', '2016-09-16 12:00:04', '', '', 'TAODA', '0', '', '', 'READWRITE', '', '', '', 'YES', '', '', '', 'DIRECTORY', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', 'DIRPOOL-3', '', '0.0', '', 'NO', '', '', '', '0', '', '2016-08-04 12:19:07', '', '2016-10-07 08:33:48', '', '0', '', 'NOLIMIT', '', '0.0', '', '', '', 'YES', ''),
('NO', '', 'PAYTON4', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', '', '', '', '', '', '90', '', 'PAYTONB', '', '', '', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2016-03-27 22:59:27', '', '', '0.0', '', '', '', '', '0.0', '', '70', '', 'NO', ''),
('', '', 'ROBOT-2-TSMGUI12', '', '', '', '1', '', 'YES', '0', '0', 'ROBOT-2-TSMGUI12-DEV', '', '', '', '', '0.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '100000000', 'READWRITE', 'NO', '', '', '', '0.0', 'Shared tape pool on TSMGUI12', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2016-04-07 08:36:19', '60', '', '', '', '', '', '', '0.0', 'GROUP', '70', '', 'NO', ''),
('', '', 'S3-CLOUD', 'ibmsp.d2158cfbf224e511bbfe40f2e9f58cf2', '', '', '', '0', '', '', '', '', '', 'OFFPREMISE', 'S3', '501383.0', '', '', '', '', '1', '', '', '0.0', 'TRICIA', '0', '', '', 'READWRITE', '', 'https://s3-us-west-1.amazonaws.com', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'tsmuser', '2016-08-09 12:50:24', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '0.0', 'YES', ''),
('NO', '', 'SPACEMGPOOL', '', '', '', '', '', 'YES', '', '0', 'DISK', '', '', '', '', '100.0', '', '', '', '', '', '90', '', 'SERVER_CONSOLE', '', '', '', 'READWRITE', 'NO', '', '', '', '0.0', '', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', 'Client', '0.0', '', 'NO', '0', 'No', '1', '', '', '2015-07-07 14:56:18', '', '', '0.0', '', '', '', '', '0.0', '', '70', '', 'NO', ''),
('', '', 'TEST', '', '', '', '', '0', '', '', '', '', '', 'ONPREMISE', 'SWIFT', '', '100.0', '', '', '', '1', '', '', '', 'CKNARVER', '0', '', '', 'READWRITE', '', 'http://www.test.com', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'test', '2016-03-14 14:24:05', '', '', '', '0', '', 'NOLIMIT', 'No', '', '', '', '', 'YES', ''),
('', '', 'TEST010101', '', '', '', '', '0', '', '', '', '', '', 'OFFPREMISE', 'SOFTLAYER', '', '100.0', '', '', '', '1', '', '', '', 'CKNARVER', '0', '', '', 'READWRITE', '', 'http://www.test.com', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'TEST1', '2016-03-16 09:22:04', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '', 'YES', ''),
('', '', 'TEST010101010101', '', '', '', '', '0', '', '', '', '', '', 'OFFPREMISE', 'SWIFT', '', '100.0', '', '', '', '1', '', '', '', 'CKNARVER', '0', '', '', 'READWRITE', '', 'http://www.yes.com', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'Jnsjsjs', '2016-04-11 08:19:17', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '', 'YES', ''),
('', '', 'TEST1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '2016-09-16 12:00:04', '', '', 'TAODA', '0', '', '', 'READWRITE', '', '', '', 'YES', '', '', '', 'DIRECTORY', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', 'DIRPOOL-1', '', '405559.0', '', 'NO', '', '', '', '0', '', '2016-08-25 10:42:19', '', '', '', '0', '', 'NOLIMIT', '', '0.0', '', '', '', 'YES', ''),
('', '', 'TEST10001', 'ibmsp.d2158cfbf224e511bbfe40f2e9f58cf2', '', '', '', '0', '', '', '', '', '', 'ONPREMISE', 'S3', '', '100.0', '', '', '', '1', '', '', '', 'CKNARVER', '0', '', '', 'READWRITE', '', 'http://www.test.com', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'test', '2016-03-16 09:02:09', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '', 'YES', ''),
('', '', 'TESTCLOUDCOMPRESS', '', '', '', '', '0', '', '', '', '', '', 'OFFPREMISE', 'SWIFT', '', '100.0', '', '', '', '1', '', '', '', 'TAODA', '0', '', '', 'READWRITE', '', 'test.test.test', '', 'YES', '', '', '', 'CLOUD', '', '', 'PRIMARY', '', '', 'NATIVE', '', '', '', '', '', '', 'NO', '', '', '', '0', 'test', '2016-03-10 10:48:17', '', '', '', '0', '', 'NOLIMIT', 'Yes', '', '', '', '', 'YES', ''),
('', '', 'VTL1-TSMGUI11', '', '', 'COPY-TAPE-TSMGUI11', '4', '', 'YES', '12', '0', 'VLT1-TSMGUI11-DEV', '', '', '', '', '100.0', '', '', '', '0', '', '90', '', 'TAODA', '', '', '30', 'READWRITE', 'NO', '', '', '', '40.0', 'VTL primary library for direct backups.', '0.0', 'DEVCLASS', 'YES', '', 'PRIMARY', '', '', 'NATIVE', 'THRESHOLD', 'NO', '', 'Client', '22598751.9', '', 'NO', '0', 'No', '1', '', '', '2016-05-11 11:21:47', '60', '', '', '', '', '', '', '4.1', 'NO', '70', '', 'NO', '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
